Repository aio-libs/aiobotocore, pull requests merged in 2025-02, with the labels that each got.

#1266 run tests on `ubuntu-24.04` and `ubuntu-24.04-arm` CI runners
  .github/workflows/ci-cd.yml
Labels: github_actions

#1286 Bump dev dependencies
  pyproject.toml
  uv.lock
Labels: dependencies

#1293 Patch `AwsChunkedWrapper.read`
  CHANGES.rst
  aiobotocore/__init__.py
  aiobotocore/httpchecksum.py
  tests/boto_tests/unit/test_httpchecksum.py
  tests/test_patches.py
Labels: bug

#1297 bump moto
  pyproject.toml
  tests/boto_tests/unit/test_signers.py
  tests/conftest.py
  tests/mock_server.py
  tests/moto_server.py
  tests/test_basic_s3.py
  uv.lock
Labels: dependencies

#1299 disable autofix PRs by pre-commit.ci
  .pre-commit-config.yaml
Labels: github_actions

#1292 Bump `botocore` dependency specification
  CHANGES.rst
  aiobotocore/httpchecksum.py
  pyproject.toml
  tests/boto_tests/unit/test_eventstream.py
  tests/test_patches.py
  uv.lock
Labels: dependencies

#1302 Bump dev dependencies
  uv.lock
Labels: dependencies

#1303 Graduate `ubuntu-24.04-arm` runners, except for Python 3.8
  .github/workflows/ci-cd.yml
Labels: github_actions

#1307 Bump `botocore` dependency specification
  CHANGES.rst
  aiobotocore/args.py
  aiobotocore/credentials.py
  aiobotocore/session.py
  pyproject.toml
  tests/boto_tests/__init__.py
  tests/boto_tests/unit/test_credentials.py
  tests/boto_tests/unit/test_session.py
  tests/test_patches.py
  uv.lock
Labels: dependencies
